name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          platform: linux
          arch: x64
        - os: ubuntu-22.04-arm64
          platform: linux
          arch: arm64
        - os: macos-14
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: windows-2022
          platform: win32
          arch: x64
        - os: windows-2022
          platform: win32
          arch: arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - if: ${{ matrix.platform == 'linux' }}
      run: |
        sudo apt update
        sudo apt install -y libgtk-4-dev
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: corestore
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: choco upgrade llvm
      if: ${{ matrix.platform == 'win32' }}
    - run: npm install -g bare-make
    - run: npm install
    - run: npm install --prefix vendor/libappling
    - run: npm install --prefix vendor/libappling/vendor/bare
    - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} ${{ matrix.flags }}
    - run: bare-make build
    - run: bare-make install --prefix install/${{ matrix.platform }}-${{ matrix.arch }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
        path: install/*
        retention-days: 5
  merge:
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: install
        merge-multiple: true
    - uses: actions/upload-artifact@v4
      with:
        name: prebuilds
        path: install
        retention-days: 5
